name: Generate

on:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Tvdb.Sdk
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - uses: actions/checkout@v3.0.1
        with:
          ref: 'master'
      - uses: actions/setup-dotnet@v2.0.0
        with:
          dotnet-version: |
            6.0.x
            5.0.x
            3.1.x
      - uses: chrisdickinson/setup-yq@latest
        with:
          yq-version: v4.9.6

      - name: Restore packages
        run: dotnet restore

      - name: Get OpenApi version
        id: apiversion
        run: |
          curl https://thetvdb.github.io/v4-api/swagger.yml -o ../swagger.yml
          echo "::set-output name=number::$(yq eval .info.version ../swagger.yml)"

      - name: Create new version string
        id: version
        run: echo "::set-output name=number::$(echo ${{ steps.apiversion.outputs.number }})"

      - name: Install dotnet-setversion
        run: dotnet tool install -g dotnet-setversion

      - name: Set project version
        run: setversion ${{steps.version.outputs.number}}

      - name: Generate
        run: dotnet msbuild -target:Generate

      - name: Check if generated client files were modified
        id: diff
        run: echo "::set-output name=count::$(git status -s | grep cs | grep -v csproj | wc -l)"

      - name: Build packages
        if: ${{ steps.diff.outputs.count > 0 }}
        run: dotnet build -c Release

      - name: Publish to nuget
        if: ${{ steps.diff.outputs.count > 0 }}
        run: dotnet nuget push bin/Release/*.nupkg --api-key ${{ secrets.NUGET_APIKEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Commit new changes to the repo
        if: ${{ steps.diff.outputs.count > 0 }}
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git pull
          git add .
          git commit --allow-empty -m "Update OpenAPI client"
          git push
